pipeline:
  batch:
    size: 125
    delay: 50

# Which directory should be used by logstash and its plugins
# for any persistent needs. Defaults to LOGSTASH_HOME/data
#
path.data: /var/lib/logstash

node:
  name: "node_${LS_NODE_NAME}"
path:
  queue: "/tmp/${QUEUE_DIR:queue}"
